# Cloud Camp Clase 7

**Numpy**

### Crear Arreglos de varias dimensiones

In [22]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [23]:
import numpy as np

v = np.arange(5)
v

array([0, 1, 2, 3, 4])

In [24]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
t = np.arange(12).reshape(3, 2, 2)
t

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [26]:
v2 = np.array([2,5,7,9]).reshape(2,2)
v2

array([[2, 5],
       [7, 9]])

In [27]:
v3 = np.arange(2,10,2)
v3

array([2, 4, 6, 8])

### Linspace

In [28]:
v4_linspace = np.linspace(9,8,10)
result_sum = v4_linspace + v4_linspace
result_sum

array([18.        , 17.77777778, 17.55555556, 17.33333333, 17.11111111,
       16.88888889, 16.66666667, 16.44444444, 16.22222222, 16.        ])

Multiplicar dos matrices

In [29]:
v5_random = np.random.rand(10)
v5_random

array([0.31066212, 0.71326573, 0.54006608, 0.7539408 , 0.48081391,
       0.62693972, 0.55518904, 0.17735737, 0.60637667, 0.02851196])

In [31]:

v6 = v5_random * v4_linspace
v6

print(v6 * 5)

[13.97979547 31.70069889 23.70290011 32.67076808 20.5681507  26.47078804
 23.13287664  7.29135865 24.59194261  1.14047841]


### Manipulación de arrays

In [33]:
m2 = np.arange(9).reshape(3,3)
m2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
print(m2[1,:])
print(m2[:,1])
print(m2[:2,:2])
print(m2[2:,2:])
print(m2[1:,1:])
print(m2.diagonal())


[3 4 5]
[1 4 7]
[[0 1]
 [3 4]]
[[8]]
[[4 5]
 [7 8]]
[2]


In [42]:
a = np.arange(4).reshape(2,2)
print(a)

# Diagonal desde la posición 0,0
a.diagonal()

a.diagonal(1)


[[0 1]
 [2 3]]


array([0, 3])

## Copiar arrays en numpy

Así no se copia :P

In [45]:
a1 = np.array([1,2,3])
a2 = a1
a1[0] = 5
a1
print("array 2")
a2


array 2


array([5, 2, 3])

In [46]:
a1 = np.array([1,2,3])
a2 = a1.copy()
a1[0] = 5
a1
print("array 2")
a2

array 2


array([1, 2, 3])